spring.application.name=toeic-defense-backend
spring.datasource.url=jdbc:mysql://localhost:3306/toeic_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Manh20112005
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.signerKey=4c6e10c9680cb914433276664cac8c82fa33f0608e022ec374df5379ef5c5ae0116227deeb217afb409231aa67a562e6a57ccf624f88005b8ac3e7769b160f72